#!/bin/bash

# Script: build_services
# Description: This script builds Gradle projects using multiple 'gradlew' scripts found in a specified directory or its subdirectories.
# Author: [Santiago C. Saavedra]
# Date: [07/09/2023]

home=$(pwd)

# Define the directory to search for 'gradlew' scripts
find_reference="$1"

# Define the name of the file to store 'gradlew' paths
gradlew_paths_name=path_names.txt

find "$find_reference" -type f -name "gradlew" >"$gradlew_paths_name"
mapfile -t main_array <"$gradlew_paths_name"
for file in "${main_array[@]}"; do
	file="$home/$file"
	(
		cd "$(dirname "$file")" || exit 1
		./gradlew -q build
		echo "Build: $(basename "$(pwd)")"
	)
done

cd "$home" || exit 1
rm "$gradlew_paths_name"
exit 0
