#!/bin/bash

# Script: fake_orgasm.sh
# Description: This script provides options to build, extract_binaries, run, and manage microservices.
# Author: [Santiago C. Saavedra]
# Date: [07/09/2023]

build=false
run=false
extract_binaries=false
logging=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build)
      build=true
      shift
      ;;
    --run)
      run=true
      shift
      ;;
    --extract-binaries)
      extract_binaries=true
      shift
      ;;
    --log)
      logging=true
      shift
      ;;
    --help)
      echo "Usage: $0 [--build] [--log] [--run] [--extract-binaries] <scripts_home>"
      echo "  --build   Build the microservices"
      echo "  --run     Run the microservices"
      echo "  --extract_binaries    Pack the binaries in a tar file"
      echo "  --log     Record stdout and stdin of the services while running"
      exit 0
      ;;
    *)
      break
      ;;
  esac
done

scripts_home=$1

binaries_folder=binaries
if ! [ -d "$binaries_folder" ]; then
  mkdir "$binaries_folder"
fi

clean_port(){
  port=$1
  if lsof -i :"$port" > /dev/null; then
    echo "Port $port is in use."
  
    # Find and kill the process using the port
    process_id=$(lsof -ti :"$port")
    if [ -n "$process_id" ]; then
      kill -9 "$process_id"
    else
      echo "Failed to find the process using the port." >&2
      exit 1
    fi
  fi
}

build(){
  "$scripts_home"/build_services backend
}

extract_binaries(){
  "$scripts_home"/extract_binaries "$binaries_folder" backend/*
}

logs_folder=logs
check_for_logging(){
  if [ "$logging" = true ]; then
    if ! [ -d "$logs_folder" ]; then
      mkdir "$logs_folder"
    fi
  fi
}

run(){
  # clean_port 8761
  check_for_logging

  services_pids_file=services_pids.txt
  binary="$scripts_home"/run_services
  if [ "$logging" = true ]; then
    log_arg="--log"
  else
    log_arg=""
  fi

  if ! "$binary" "$scripts_home"/service_execution_order.txt "$binaries_folder" > "$services_pids_file" "$log_arg"; then
    echo "Could not start the running script, please check the binary folder" >&2
    rm "$services_pids_file"
    exit 1
  fi

  cat "$services_pids_file"
  tmp="$services_pids_file"
  awk '{ print $4 }' "$tmp" > "$services_pids_file"

  # Kill services based on PIDs in the services_pids_file
  read -rp "Press enter to kill services"
  while IFS= read -r line; do
    kill -9 "$line"
  done < "$services_pids_file"
  rm "$services_pids_file"
  lsof -i :8761 | awk '{{print $2}}' | xargs -n 1 kill -q -9 2>/dev/null
}

if [ "$build" = true ]; then
  build
fi

if [ "$extract_binaries" = true ]; then
  extract_binaries
fi

if [ "$run" = true ]; then
  run
fi

exit 0
