#! /bin/bash

packaging_dir="$1"
package_name=fake_orgasm_app.tar
shift
for folder in "$@"; do
	folder_path="$folder/build/distributions/"
	if [ -d "$folder_path" ]; then
		find "$folder_path" -type f -name "*boot*.tar" -exec tar -xf {} -C "$folder_path" \;
		bin_path=$(find "$folder_path" -type d -name "bin" -exec dirname {} \;)
		cp -r "$bin_path" "$packaging_dir"
	else
		printf "Path: %s does not exist\n" "$folder_path"
		exit 1
	fi
done

tar -cf "$package_name" "$packaging_dir"
echo "Binaries packed at: $(realpath $package_name)"
exit 0
