name: Develop 🏗️ 
run-name: ${{ github.actor }} is executing the workflow ${{ github.workflow }}.

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
      - main

jobs:
  build:
    name: build
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'gradle'

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          ./gradlew build -x test -x check --no-daemon

  test:
    name: test
    needs: build
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'gradle'

      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          ./gradlew test -x check --no-daemon

  check:
    name: code_analysis 
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'gradle'

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          cd backend
          ./gradlew checkStyleMain spotlessCheck -x checkStyleTest -x test

